#!/bin/bash
# SessionStart: put the knowledge index into EVERY session's context — the
# project's own claims where they exist, and ALWAYS the cross-project laws.
#
# WHY IT NEVER GOES SILENT (2026-08-20). Ryan: "And how will future projects
# never make these mistakes? And when I start a new project, how will I know
# about information retrieval?"
#
# The first version exited 0 when a project had no knowledge/ dir — which is
# precisely the session that needs telling. A new project starts empty and
# would re-derive every cross-project lesson from scratch, which is the failure
# this whole mechanism exists to stop, reappearing one level up. So the
# universal store is injected everywhere, and a project without its own store is
# told how to make one in the same breath.
#
# Markdown files require someone to remember to read them, and the thing that
# fails between sessions is remembering. So the index is PUSHED, not pulled, in
# its one-line form: cheap enough to sit in every session, with the full claim
# one command away.

# --- VENDORED RESOLVER (added 2026-08-21, Tier 1 hardening) ------------------
# A vendored hook that still reaches into $HOME is not vendored -- it works only
# on the author's machine, which is the exact failure this vendoring exists to
# fix. Resolve tools NEXT TO THIS FILE first, and fall back to the home store
# only when this copy is incomplete.
_KHERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
if [ -f "$_KHERE/../check-knowledge.py" ]; then
  KBIN="$_KHERE/.."
  KHOOKS="$_KHERE"
else
  KBIN="$HOME/.claude/knowledge/bin"
  KHOOKS="$HOME/.claude/hooks"
fi
KUNIVERSAL="${KUNIVERSAL:-$KUNIVERSAL}"
# ----------------------------------------------------------------------------

set -u
BIN="$KBIN/find-technique.py"
UNIVERSAL="$KUNIVERSAL"
[ -f "$BIN" ] || exit 0

d=$(pwd -P); store=""
while [ "$d" != "/" ]; do
  if [ -d "$d/knowledge" ] && ls "$d/knowledge"/*.md >/dev/null 2>&1; then
    store="$d/knowledge"; break
  fi
  d=$(dirname "$d")
done

# PENDING VERDICTS FIRST, ABOVE EVERYTHING. A question awaiting a person is the
# most perishable thing in the system: the evidence scrolls away, the window
# closes, the context compacts, and what is lost is a decision that was one
# sentence from being made. It is also the only item here the agent CANNOT
# resolve alone, so burying it below the index would be exactly backwards.
ASK="$KBIN/knowledge-ask.py"
PENDING=""
if [ -n "$store" ] && [ -f "$ASK" ]; then
  pend=$(python3 "$ASK" --list --dir "$store" 2>/dev/null)
  if [ -n "$pend" ]; then
    PENDING="## ⏳ AWAITING A HUMAN — raise these BEFORE new work

These are answered questions away from unblocking real work, and nobody but the
person named can settle them. RAISE THEM EARLY IN THE SESSION, and \`open\` every
file listed under LOOK AT in the same message — naming a visual without putting
it on screen is the show-me-pixels law, and an unanswerable ask is why these
died before.

Settle one with:
    knowledge-ask.py --answer <id> --verdict \"what they decided\"
then write the claim their answer justifies — the verdict is not the knowledge,
the rule it establishes is.

\`\`\`
$pend
\`\`\`

"
  fi
fi

HEAD="${PENDING}## Knowledge store (SessionStart hook)

Decisions already MEASURED, typed so they can be checked and retired. A LAW is
absolute. A REFUTED entry is a dead end someone already paid for — do not retry
it. A VERDICT is true only inside its stated scope. An OPEN item is a plan, not
a spec. **Query before choosing any technique rather than reading this index:**

    python3 ~/.claude/knowledge/bin/find-technique.py \"<your situation>\"

Every claim declares \`asked-as\` — the questions that must find it — and
\`check-retrieval.py\` asserts they do, at write time. Writing something down and
being able to find it are independent problems; only the first feels like work.
"

if [ -n "$store" ]; then
  idx=$(python3 "$BIN" --brief --dir "$store" 2>/dev/null)
  uni=$(python3 "$BIN" --brief --dir "$UNIVERSAL" 2>/dev/null)
  CTX="$HEAD
### This project
\`\`\`
${idx:-(empty)}
\`\`\`

### Cross-project laws (~/.claude/knowledge/store — searched from everywhere)
\`\`\`
${uni:-(none)}
\`\`\`

**When Ryan says \"bookmark that\" (or park / note / don't forget / come back to
this), invoke the \`bookmark\` skill immediately and reply in ONE line.** He may
then open a new tab and tell a fresh instance to go work that bookmark, so each
one must stand alone. It is easy to try to fix everything at once and finish
nothing; a bookmark is how a good idea stops derailing the current task.
STATE.md is GENERATED by state-report.py — do not hand-edit it."
else
  uni=$(python3 "$BIN" --brief --dir "$UNIVERSAL" 2>/dev/null)
  [ -n "$uni" ] || exit 0
  CTX="$HEAD
### ⚠ THIS PROJECT HAS NO KNOWLEDGE STORE

Create one before the first discovery is made, because the failure it prevents
is a discovery going somewhere untyped and unqueryable:

    python3 ~/.claude/knowledge/bin/knowledge-init.py

**Say \"bookmark that\" at any time and it will be created for you** — the
\`bookmark\` skill makes the store on the spot if there is none. Then write the
project's LAWS first (the user's own words), then the dead ends with MECHANISMS. Three layers, and only one is typed by hand: CLAIMS go in
\`knowledge/\`, NARRATIVE in \`docs/journal/\` and commit messages, STATUS is
GENERATED into STATE.md by \`state-report.py\`.

### Cross-project laws — these apply here already
\`\`\`
$uni
\`\`\`"
fi

jq -n --arg ctx "$CTX" '{hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:$ctx}}'
