#!/usr/bin/env python3
"""Generate a project's STATE.md from sources that cannot go stale. One job.

WHY THIS EXISTS (2026-08-20). Ryan: "Fix STATE.md too — migrate it into the
store. This needs to be robust across multiple sessions and projects."

jobs/wang-meng/STATE.md had reached 896 hand-written, append-only lines, and it
was three different documents sharing a filename:

  CLAIMS      "Frame-zero control on every fill/extend: 0 px changed at rest"
  NARRATIVE   forty dated entries of what was tried and what happened
  STATUS      what exists right now, what is next, where files live

Only one of those should be typed by a human, and it is not the one people
type. The proof: that frame-zero law sat in the file since 2026-08-17 and was
RE-DERIVED on 2026-08-20 at the cost of four wrong parameter passes, because a
numbered prose list is not queryable. LAW 7 of the same list ("click TRUNKS not
canopies") was violated the same afternoon. The knowledge did not need to be
discovered. It needed to be retrievable.

So each part goes where it can be checked:

  CLAIMS     -> knowledge/, typed, one live answer per question, findability
                tested at write time by check-retrieval.py
  NARRATIVE  -> docs/journal/ and git, which already hold it for free
  STATUS     -> GENERATED, by this tool, from git + the store + the project's
                own status script. Never appended to, never hand-edited.

A hand-written status file is a cache of the repo with no invalidation. It
drifts silently, and the drift is invisible precisely because it reads fluently.
This one is rebuilt from the repo every time, so it cannot lie for longer than
one run.

WHAT IT IS NOT FOR. Anything a human needs to SAY. If it is a decision, a
measurement or a rule, it is a claim -- write it with knowledge-bookmark.py or
by hand into knowledge/, where it will be type-checked and retrieval-tested.
Text typed into STATE.md is destroyed on the next run, deliberately.

Per-project operational numbers come from an OPTIONAL executable at
`knowledge/status.sh`, which prints whatever that project counts (zones built,
tests passing, endpoints live). Generic here; specific there.

usage:
  state-report.py [--out STATE.md] [--dir knowledge] [--commits 12] [--stdout]
"""
import argparse, os, subprocess, sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
BANNER = ("<!-- GENERATED by state-report.py — DO NOT EDIT. Hand edits are "
          "destroyed on the next run.\n     Knowledge goes in knowledge/ "
          "(typed, queryable). Narrative goes in docs/journal/. -->")


def run(cmd, cwd=None, timeout=30):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, timeout=timeout)
        return r.stdout.rstrip() if r.returncode == 0 else ''
    except Exception:
        return ''


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--out', default='STATE.md')
    p.add_argument('--dir', default=None, help='knowledge store (default: nearest above cwd)')
    p.add_argument('--commits', type=int, default=12)
    p.add_argument('--stdout', action='store_true')
    a = p.parse_args()

    import importlib.util
    spec = importlib.util.spec_from_file_location("_ck", HERE / "check-knowledge.py")
    ck = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ck)
    store = Path(a.dir) if a.dir else ck.find_store()
    root = store.parent

    L = [BANNER, '', f'# {root.name} — STATE',
         '', f'*Generated {datetime.now():%Y-%m-%d %H:%M} from git, the knowledge '
             f'store, and this project\'s own status script. Nothing here is typed '
             f'by hand, so nothing here can be stale.*', '']

    # ── 1. WHAT TO DO NEXT — the open claims ARE the work order ──────────────
    openq = run([sys.executable, str(HERE / 'knowledge-bookmark.py'),
                 '--list', '--dir', str(store)])
    L += ['## What is open', '',
          'Every `kind: open` claim in the store. These are PLANS, not specs — '
          '`proven: false`. Do not build against one without a verdict.', '',
          '```', openq or '(none)', '```', '']

    # ── 2. WHAT THIS PROJECT KNOWS ───────────────────────────────────────────
    brief = run([sys.executable, str(HERE / 'find-technique.py'),
                 '--brief', '--dir', str(store)])
    L += ['## What this project knows', '',
          'The full index. Query it before choosing any technique — '
          '`find-technique.py "<your situation>"` — rather than reading it. '
          'Every claim declares the questions that must find it, and '
          '`check-retrieval.py` asserts they do.', '',
          '```', brief or '(empty store — run knowledge-init.py)', '```', '']

    # ── 3. OPERATIONAL STATUS — the project speaks for itself ────────────────
    st = store / 'status.sh'
    if st.exists() and os.access(st, os.X_OK):
        out = run(['bash', str(st)], cwd=root, timeout=120)
        L += ['## Where the work stands', '',
              f'*From `{st.relative_to(root)}`, run at generation time.*', '',
              '```', out or '(status script printed nothing)', '```', '']
    else:
        L += ['## Where the work stands', '',
              f'*No `{(store / "status.sh").relative_to(root)}` in this project.* '
              'Add an executable script there that prints whatever this project '
              'counts — built artefacts, passing tests, live endpoints — and it '
              'will be run and inlined here on every generation.', '']

    # ── 4. NARRATIVE — git already holds it ──────────────────────────────────
    log = run(['git', 'log', f'-{a.commits}', '--date=short',
               '--pretty=format:%ad  %h  %s'], cwd=root)
    L += ['## Recent history', '',
          '*From git. The full narrative lives in `docs/journal/`; commit '
          'subjects are written as search bait, so `git log --grep` is the '
          'index.*', '', '```', log or '(not a git repo)', '```', '']

    # THE REMOTE IS CHECKED, NOT ASSUMED (law: everything-lives-in-a-remote-repo).
    # A local-only repo does not survive a disk, does not reach a second machine,
    # and cannot make a rule apply anywhere but where it was written. Measured
    # 2026-08-20: nine cross-project laws sat on one disk with no origin while
    # the project that used them was on GitHub.
    remote = run(['git', 'remote', 'get-url', 'origin'], cwd=root)
    if not remote:
        L += ['### ⚠ NO REMOTE', '',
              'This repository has no `origin`. Everything in it is one disk failure '
              'from gone, and none of it reaches another machine. Fix now:', '',
              '```', 'gh repo create <name> --private --source=. --remote=origin --push',
              '```', '']
    else:
        br = run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=root)
        ahead = run(['git', 'rev-list', '--count', f'origin/{br}..HEAD'], cwd=root)
        if ahead and ahead != '0':
            L += ['### ⚠ UNPUSHED', '',
                  f'**{ahead} commit(s) ahead of `origin/{br}`.** Committed is not '
                  f'the same as safe — a commit that has not left this machine has '
                  f'the durability of the disk it is on.', '', '```',
                  f'git push origin {br}', '```', '']
        else:
            L += [f'*Remote: `{remote}` — `{br}` is pushed.*', '']

    dirty = run(['git', 'status', '--short'], cwd=root)
    if dirty:
        L += ['### Uncommitted', '', '```', dirty, '```',
              '', '*Uncommitted is not learned. Commit at the moment of learning.*', '']

    L += ['---', '',
          '**Where things go.** A rule, a measurement or a decision is a CLAIM → '
          '`knowledge/`, typed and queryable. What was tried and what happened is '
          'NARRATIVE → `docs/journal/` and the commit message. What exists right '
          'now is STATUS → generated here, from the repo. Nothing is appended to '
          'this file, because an append-only status page is a cache of the '
          'repository with no invalidation.', '']

    text = '\n'.join(L)
    if a.stdout:
        print(text)
    else:
        out = Path(a.out)
        if not out.is_absolute():
            out = root / a.out
        prev = out.read_text() if out.exists() else ''
        if prev and BANNER.split('\n')[0] not in prev:
            bak = out.with_suffix('.pre-migration.md')
            bak.write_text(prev)
            print(f'hand-written {out.name} preserved at {bak.name} — migrate its '
                  f'CLAIMS into {store.name}/ before deleting it', file=sys.stderr)
        out.write_text(text)
        print(f'{out}  ({len(text.splitlines())} lines, generated)', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
