#!/usr/bin/env python3
"""Assemble one shot from a still plate and several animated regions. One job.

A finished shot is not one clip. It is a motionless painting plus a river running
in one region, leaves stirring in another, mist drifting in a third -- each
generated by whatever method suits that material, each confined to its own mask.
This is the last step that puts them in the same picture.

Each --layer is CLIP:MASKDIR[:NAME]. The clip must be the same size as the plate
and must agree with the plate outside its own mask; both hold for anything
stroke-cycle.py produced. Layers are applied in the order given, so a later layer
wins where two masks overlap.

  ./composite-shot.py --plate P.png --out O.mp4 \\
      --layer cel-medium.mp4:mask/water:upper-river \\
      --layer sway-breeze.mp4:mask/canopy
"""
import argparse, json, subprocess
from pathlib import Path
import numpy as np
from PIL import Image, ImageFilter

p = argparse.ArgumentParser()
p.add_argument('--plate', required=True); p.add_argument('--out', required=True)
p.add_argument('--layer', required=True, action='append')
p.add_argument('--feather', type=int, default=8); p.add_argument('--fps', type=float, default=24)
a = p.parse_args()

plate = np.array(Image.open(a.plate).convert('RGB')).astype(np.float32)
H, W = plate.shape[:2]

def read(path):
    pr = json.loads(subprocess.run(
        ['ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries',
         'stream=width,height', '-of', 'json', path], capture_output=True, text=True).stdout)
    w, h = pr['streams'][0]['width'], pr['streams'][0]['height']
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', path, '-f', 'rawvideo',
                          '-pix_fmt', 'rgb24', '-'], capture_output=True).stdout
    return np.frombuffer(raw, np.uint8).reshape(-1, h, w, 3), (w, h)

layers, report = [], []
for spec in a.layer:
    parts = spec.split(':')
    clip, mdir, only = parts[0], parts[1], (parts[2] if len(parts) > 2 else None)
    frames, (w, h) = read(clip)
    if (w, h) != (W, H):
        raise SystemExit(f'{clip} is {w}x{h}, plate is {W}x{H}')
    m = np.zeros((H, W), np.float32)
    used = []
    for pl in json.load(open(Path(mdir) / 'layers.json'))['planeList']:
        if only and pl['name'] != only:
            continue
        mi = np.array(Image.open(Path(mdir) / 'masks' / f"{pl['n']:03d}.png").convert('L'), np.float32) / 255
        ox, oy = pl['offset']; mh, mw = mi.shape
        m[oy:oy + mh, ox:ox + mw] = np.maximum(m[oy:oy + mh, ox:ox + mw], mi)
        used.append(pl['name'])
    if a.feather:
        m = np.array(Image.fromarray((m * 255).astype(np.uint8))
                     .filter(ImageFilter.GaussianBlur(a.feather)), np.float32) / 255
    layers.append((frames, m[..., None]))
    report.append({'clip': clip, 'regions': used, 'frames': int(frames.shape[0]),
                   'coveragePct': round(float((m > 0.5).mean()) * 100, 2)})

n = min(f.shape[0] for f, _ in layers)
enc = subprocess.Popen(
    ['ffmpeg', '-y', '-v', 'error', '-f', 'rawvideo', '-pix_fmt', 'rgb24',
     '-s', f'{W}x{H}', '-r', str(a.fps), '-i', '-', '-c:v', 'libx264', '-crf', '15',
     '-pix_fmt', 'yuv420p', a.out], stdin=subprocess.PIPE)
for i in range(n):
    out = plate.copy()
    for frames, m in layers:
        out = out * (1 - m) + frames[i].astype(np.float32) * m
    enc.stdin.write(np.clip(out, 0, 255).astype(np.uint8).tobytes())
enc.stdin.close(); enc.wait()

print(json.dumps({'out': a.out, 'frames': n, 'layers': report,
                  'note': 'plate is motionless; everything that moves is inside a '
                          'named mask, which is what keeps Ge Hong out of it'}, indent=2))
